# Generated by Django 5.0.2 on 2024-02-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='company_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
