# Generated by Django 5.0.2 on 2024-02-15 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=150)),
                ('product_no', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
            options={
                'db_table': 'product_tb',
            },
        ),
    ]
