# Generated by Django 5.0.2 on 2024-02-22 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eKart_admin', '0002_category'),
        ('seller', '0003_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eKart_admin.category'),
        ),
    ]
